### PR TITLE
Document how to turn off GOV.UK Account

### PR DESCRIPTION
**Pull request by jonathanglassman**
Document how to turn off GOV.UK Account, as per trello card: https://trello.com/c/Kh2Ht06d/561-document-switch-off-accounts

### CODE REVIEW

**Comment by jonathanglassman** [comment]
Will need to remove https://team-manual.account.publishing.service.gov.uk/support/resolve/#i-need-to-switch-off-the-account-manager-entirely

**Comment by huwd** [comment]
So close on this now, just need to see the following merged:
- https://github.com/alphagov/govuk-account-manager-prototype/pull/587
- https://github.com/alphagov/finder-frontend/pull/2389

Then will get you some screenshots of the pipeline if that helps?

**Comment by jonathanglassman** [comment]
> So close on this now, just need to see the following merged:
> 
> * [alphagov/govuk-account-manager-prototype#587](https://github.com/alphagov/govuk-account-manager-prototype/pull/587)
> * [alphagov/finder-frontend#2389](https://github.com/alphagov/finder-frontend/pull/2389)
> 
> Then will get you some screenshots of the pipeline if that helps?

yes please

**Comment by jonathanglassman** [comment]
@huwd the content changes we discussed yesterday are in the PR. please review when you have time

**Review by huwd — COMMENTED** [review]
Looks great

**Review by huwd — APPROVED** [review]

**Pull request merged**
